services:
    user_admin:
        class: Objects\MongoDBAdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: User }
        arguments: [null, Objects\MongoDBUserBundle\Document\User, ObjectsMongoDBAdminBundle:UserAdmin]
